/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feesmanagment;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.*;
import java.io.*; 
import java.util.HashSet;
import java.util.Set;
import javafx.stage.FileChooser;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Adnan
 */
public class Admin_home extends javax.swing.JFrame {
    Connect c=new Connect();
    public String name;
    public void label(String s)
    {
        
    label_name.setText("Role Played By:-"+s);
    }
    
    void showDateTime() {
        new Timer(0, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
                SimpleDateFormat sd = new SimpleDateFormat("hh:mm:ss a");
                label_datetime.setText("Date :-" + s.format(d) + " Time :-" + sd.format(d));
            }
        }).start();

    }

    void table_cashier(){
        try
        {
           
            String q="SELECT * FROM `cashier_details`";
            c.rs=c.st.executeQuery(q);
                                 while(c.rs.next())
                                {
                                         String id=c.rs.getString(1);
                                         String user=c.rs.getString(2);
                                         String password=c.rs.getString(3);
                                         String address=c.rs.getString(4);
                                         String contect=c.rs.getString(5);
                                         String email=c.rs.getString(6);
                                         String status=c.rs.getString(7);
                                         Object [] content={id,user,password,address,contect,email,status};
                                         DefaultTableModel m1=(DefaultTableModel)table_cashierhome.getModel();
                                         m1.addRow(content);
                                         DefaultTableModel model=(DefaultTableModel) table_cashier.getModel();
                                         model.addRow(content);
                               }
           }
           catch(Exception a )
           {
                   JOptionPane.showMessageDialog(this,"Exception Is"+a.getMessage());
           }
    }
    public Admin_home() {
        
      
         this.setUndecorated(true); //remove title bar
       // this.setAlwaysOnTop(true); //for top
         this.setResizable(false);
         initComponents();
         showDateTime();
         table_cashier();
         course_table();
         panel_home.setVisible(true);
         panel_addcashier.setVisible(false);
        panel_managecourse.setVisible(false);
        panel_transaction.setVisible(false);
    }

    Admin_home(String user) {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_home = new javax.swing.JPanel();
        btn_minimize = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_cashierhome = new javax.swing.JTable();
        label = new javax.swing.JLabel();
        label_datetime = new javax.swing.JLabel();
        btn_backupdatabase = new javax.swing.JButton();
        text_backuppath = new javax.swing.JTextField();
        btn_backupdatabase1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        label2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        admin_slidepanel = new javax.swing.JPanel();
        panel_adminlogout = new javax.swing.JPanel();
        adminbtn_logout = new javax.swing.JButton();
        panel_adminmanagefees = new javax.swing.JPanel();
        adminbtn_managecourse = new javax.swing.JButton();
        panel_adminaddcashier = new javax.swing.JPanel();
        adminbtn_addcashier = new javax.swing.JButton();
        panel_adminhome = new javax.swing.JPanel();
        adminbtn_home = new javax.swing.JButton();
        label_name = new javax.swing.JLabel();
        label_titlebar1 = new javax.swing.JLabel();
        panel_addcashier = new javax.swing.JPanel();
        btn_minimize2 = new javax.swing.JButton();
        btn_close2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        text_cashieremail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_cashierusername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combobox_status = new javax.swing.JComboBox<>();
        btn_exportexcelsheetcashier = new javax.swing.JButton();
        btn_addcashier = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        text_cashierid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text_cashierpassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text_cashiercontect = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        text_cashieraddress = new javax.swing.JTextArea();
        btn_updatecashier = new javax.swing.JButton();
        btn_deletecashier = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_cashier = new javax.swing.JTable();
        btn_clearaddcashier1 = new javax.swing.JButton();
        text_searchcashier = new javax.swing.JTextField();
        btn_refrashmanagecashier = new javax.swing.JButton();
        panel_managecourse = new javax.swing.JPanel();
        btn_minimize3 = new javax.swing.JButton();
        btn_close3 = new javax.swing.JButton();
        label_addnewcourse = new javax.swing.JLabel();
        text_searchcoursefees = new javax.swing.JTextField();
        label_courseid = new javax.swing.JLabel();
        text_courseid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_updatecourse = new javax.swing.JButton();
        btn_addcourse = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_coursedesc = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_course = new javax.swing.JTable();
        text_coursefees = new javax.swing.JTextField();
        btn_refrashtable = new javax.swing.JButton();
        btn_deletecourse = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        label_coursename1 = new javax.swing.JLabel();
        text_coursename = new javax.swing.JTextField();
        btn_clearcourse = new javax.swing.JButton();
        panel_transaction = new javax.swing.JPanel();
        btn_minimize1 = new javax.swing.JButton();
        btn_close1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_transaction = new javax.swing.JTable();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_home.setBackground(new java.awt.Color(255, 255, 255));
        panel_home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_home.setPreferredSize(new java.awt.Dimension(260, 768));
        panel_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize_window.png"))); // NOI18N
        btn_minimize.setContentAreaFilled(false);
        btn_minimize.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizeActionPerformed(evt);
            }
        });
        panel_home.add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 50, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window.png"))); // NOI18N
        btn_close.setContentAreaFilled(false);
        btn_close.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        panel_home.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 50, -1));

        table_cashierhome.setAutoCreateRowSorter(true);
        table_cashierhome.setBackground(new java.awt.Color(0, 181, 204));
        table_cashierhome.setBorder(new javax.swing.border.MatteBorder(null));
        table_cashierhome.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        table_cashierhome.setForeground(new java.awt.Color(255, 255, 255));
        table_cashierhome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Username", "Password", "Address", "Contect No", "Email Address", "Status"
            }
        ));
        table_cashierhome.setEnabled(false);
        table_cashierhome.setFocusable(false);
        table_cashierhome.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_cashierhome.setRowHeight(20);
        table_cashierhome.setSelectionBackground(new java.awt.Color(0, 181, 255));
        table_cashierhome.setShowVerticalLines(true
        );
        table_cashierhome.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_cashierhome);

        panel_home.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 950, 310));

        label.setBackground(new java.awt.Color(0, 181, 204));
        label.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        label.setText("Backup DataBase");
        panel_home.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, -1));

        label_datetime.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        label_datetime.setForeground(new java.awt.Color(0, 181, 204));
        label_datetime.setText("Time:-");
        panel_home.add(label_datetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 30));

        btn_backupdatabase.setBackground(new java.awt.Color(0, 181, 204));
        btn_backupdatabase.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        btn_backupdatabase.setText("Browse Path");
        btn_backupdatabase.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_backupdatabase.setContentAreaFilled(false);
        btn_backupdatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backupdatabaseActionPerformed(evt);
            }
        });
        panel_home.add(btn_backupdatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 160, 40));

        text_backuppath.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        text_backuppath.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_backuppath.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        text_backuppath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_backuppathActionPerformed(evt);
            }
        });
        panel_home.add(text_backuppath, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 470, 40));

        btn_backupdatabase1.setBackground(new java.awt.Color(0, 181, 204));
        btn_backupdatabase1.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        btn_backupdatabase1.setText("Backup Database");
        btn_backupdatabase1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_backupdatabase1.setContentAreaFilled(false);
        btn_backupdatabase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backupdatabase1ActionPerformed(evt);
            }
        });
        panel_home.add(btn_backupdatabase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 160, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panel_home.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1060, 10));

        label2.setBackground(new java.awt.Color(0, 181, 204));
        label2.setFont(new java.awt.Font("Segoe UI Light", 1, 25)); // NOI18N
        label2.setText("Available Cashier");
        panel_home.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 40));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panel_home.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 910, 10));

        getContentPane().add(panel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1140, 1020));

        admin_slidepanel.setBackground(new java.awt.Color(0, 181, 204));
        admin_slidepanel.setPreferredSize(new java.awt.Dimension(270, 768));
        admin_slidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_adminlogout.setBackground(new java.awt.Color(255, 0, 0));
        panel_adminlogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminbtn_logout.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        adminbtn_logout.setForeground(new java.awt.Color(255, 255, 255));
        adminbtn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-rounded-left-32.png"))); // NOI18N
        adminbtn_logout.setText("Logout");
        adminbtn_logout.setContentAreaFilled(false);
        adminbtn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn_logoutActionPerformed(evt);
            }
        });
        panel_adminlogout.add(adminbtn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        admin_slidepanel.add(panel_adminlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 240, 70));

        panel_adminmanagefees.setBackground(new java.awt.Color(255, 255, 255));
        panel_adminmanagefees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminbtn_managecourse.setBackground(new java.awt.Color(255, 255, 255));
        adminbtn_managecourse.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        adminbtn_managecourse.setForeground(new java.awt.Color(0, 181, 204));
        adminbtn_managecourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-course-32.png"))); // NOI18N
        adminbtn_managecourse.setText("Manage Course");
        adminbtn_managecourse.setContentAreaFilled(false);
        adminbtn_managecourse.setSelected(true);
        adminbtn_managecourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn_managecourseActionPerformed(evt);
            }
        });
        panel_adminmanagefees.add(adminbtn_managecourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        admin_slidepanel.add(panel_adminmanagefees, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 240, 70));

        panel_adminaddcashier.setBackground(new java.awt.Color(255, 255, 255));
        panel_adminaddcashier.setForeground(new java.awt.Color(0, 181, 204));
        panel_adminaddcashier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminbtn_addcashier.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        adminbtn_addcashier.setForeground(new java.awt.Color(0, 181, 204));
        adminbtn_addcashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-salary-male-32 (1).png"))); // NOI18N
        adminbtn_addcashier.setText("Manage Cashier");
        adminbtn_addcashier.setContentAreaFilled(false);
        adminbtn_addcashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn_addcashierActionPerformed(evt);
            }
        });
        panel_adminaddcashier.add(adminbtn_addcashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        admin_slidepanel.add(panel_adminaddcashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 240, 70));

        panel_adminhome.setBackground(new java.awt.Color(255, 255, 255));
        panel_adminhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminbtn_home.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        adminbtn_home.setForeground(new java.awt.Color(0, 181, 204));
        adminbtn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-32.png"))); // NOI18N
        adminbtn_home.setText("Home");
        adminbtn_home.setContentAreaFilled(false);
        adminbtn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn_homeActionPerformed(evt);
            }
        });
        panel_adminhome.add(adminbtn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        admin_slidepanel.add(panel_adminhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 240, 70));

        label_name.setBackground(new java.awt.Color(255, 255, 255));
        label_name.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        label_name.setForeground(new java.awt.Color(255, 255, 255));
        admin_slidepanel.add(label_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 40));

        label_titlebar1.setBackground(new java.awt.Color(0, 181, 204));
        label_titlebar1.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        label_titlebar1.setForeground(new java.awt.Color(255, 255, 255));
        label_titlebar1.setText("Admin Dashboard");
        admin_slidepanel.add(label_titlebar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 40));

        getContentPane().add(admin_slidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 768));

        panel_addcashier.setBackground(new java.awt.Color(255, 255, 255));
        panel_addcashier.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_addcashier.setPreferredSize(new java.awt.Dimension(260, 768));
        panel_addcashier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimize2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize_window.png"))); // NOI18N
        btn_minimize2.setContentAreaFilled(false);
        btn_minimize2.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_minimize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimize2ActionPerformed(evt);
            }
        });
        panel_addcashier.add(btn_minimize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 50, 50));

        btn_close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window.png"))); // NOI18N
        btn_close2.setContentAreaFilled(false);
        btn_close2.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_close2ActionPerformed(evt);
            }
        });
        panel_addcashier.add(btn_close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 50, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N
        jLabel2.setText("Add new Cashier");
        panel_addcashier.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -130, 540, 70));

        text_cashieremail.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        text_cashieremail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_cashieremail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cashieremailActionPerformed(evt);
            }
        });
        panel_addcashier.add(text_cashieremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 360, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel3.setText("Manage Cashier");
        panel_addcashier.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 390, 50));

        text_cashierusername.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        text_cashierusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_cashierusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cashierusernameActionPerformed(evt);
            }
        });
        panel_addcashier.add(text_cashierusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 360, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jLabel4.setText("Status");
        panel_addcashier.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 90, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jLabel5.setText("Email Address");
        panel_addcashier.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 100, 50));

        combobox_status.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        combobox_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "In-Active" }));
        combobox_status.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        panel_addcashier.add(combobox_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 350, 50));

        btn_exportexcelsheetcashier.setBackground(new java.awt.Color(0, 181, 204));
        btn_exportexcelsheetcashier.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        btn_exportexcelsheetcashier.setText("Export to Excelsheet");
        btn_exportexcelsheetcashier.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_exportexcelsheetcashier.setContentAreaFilled(false);
        btn_exportexcelsheetcashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportexcelsheetcashierActionPerformed(evt);
            }
        });
        panel_addcashier.add(btn_exportexcelsheetcashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 150, 30));

        btn_addcashier.setBackground(new java.awt.Color(0, 181, 204));
        btn_addcashier.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        btn_addcashier.setText("Add");
        btn_addcashier.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_addcashier.setContentAreaFilled(false);
        btn_addcashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcashierActionPerformed(evt);
            }
        });
        panel_addcashier.add(btn_addcashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 180, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jLabel6.setText("Username");
        panel_addcashier.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jLabel7.setText("Cashier Id");
        panel_addcashier.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 50));

        text_cashierid.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        text_cashierid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_cashierid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cashieridActionPerformed(evt);
            }
        });
        panel_addcashier.add(text_cashierid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 360, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jLabel9.setText("Password");
        panel_addcashier.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 50));

        text_cashierpassword.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        text_cashierpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_cashierpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cashierpasswordActionPerformed(evt);
            }
        });
        panel_addcashier.add(text_cashierpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 360, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jLabel11.setText("Address");
        panel_addcashier.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jLabel12.setText("Contact no");
        panel_addcashier.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 100, 50));

        text_cashiercontect.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        text_cashiercontect.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_cashiercontect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cashiercontectActionPerformed(evt);
            }
        });
        panel_addcashier.add(text_cashiercontect, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 360, 40));

        jScrollPane5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jScrollPane5.setForeground(new java.awt.Color(0, 181, 204));

        text_cashieraddress.setColumns(20);
        text_cashieraddress.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        text_cashieraddress.setRows(5);
        jScrollPane5.setViewportView(text_cashieraddress);

        panel_addcashier.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 360, 80));

        btn_updatecashier.setBackground(new java.awt.Color(0, 181, 204));
        btn_updatecashier.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        btn_updatecashier.setText("Update");
        btn_updatecashier.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_updatecashier.setContentAreaFilled(false);
        btn_updatecashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatecashierActionPerformed(evt);
            }
        });
        panel_addcashier.add(btn_updatecashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 180, 50));

        btn_deletecashier.setBackground(new java.awt.Color(0, 181, 204));
        btn_deletecashier.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        btn_deletecashier.setText("Delete");
        btn_deletecashier.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_deletecashier.setContentAreaFilled(false);
        btn_deletecashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletecashierActionPerformed(evt);
            }
        });
        panel_addcashier.add(btn_deletecashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 180, 50));

        table_cashier.setAutoCreateRowSorter(true);
        table_cashier.setBackground(new java.awt.Color(0, 181, 204));
        table_cashier.setBorder(new javax.swing.border.MatteBorder(null));
        table_cashier.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        table_cashier.setForeground(new java.awt.Color(255, 255, 255));
        table_cashier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Username", "Password", "Address", "Contect No", "Email", "Status"
            }
        ));
        table_cashier.setFocusable(false);
        table_cashier.setRowHeight(30);
        table_cashier.setRowMargin(5);
        table_cashier.setSelectionBackground(new java.awt.Color(51, 51, 255));
        table_cashier.setShowVerticalLines(true
        );
        table_cashier.getTableHeader().setReorderingAllowed(false);
        table_cashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_cashierMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table_cashier);
        if (table_cashier.getColumnModel().getColumnCount() > 0) {
            table_cashier.getColumnModel().getColumn(0).setPreferredWidth(20);
            table_cashier.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        panel_addcashier.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 500, 520));

        btn_clearaddcashier1.setBackground(new java.awt.Color(0, 181, 204));
        btn_clearaddcashier1.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        btn_clearaddcashier1.setText("Clear");
        btn_clearaddcashier1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_clearaddcashier1.setContentAreaFilled(false);
        btn_clearaddcashier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearaddcashier1ActionPerformed(evt);
            }
        });
        panel_addcashier.add(btn_clearaddcashier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 180, 50));

        text_searchcashier.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        text_searchcashier.setText("Search Course");
        text_searchcashier.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_searchcashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_searchcashierMouseClicked(evt);
            }
        });
        text_searchcashier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_searchcashierKeyReleased(evt);
            }
        });
        panel_addcashier.add(text_searchcashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 440, 50));

        btn_refrashmanagecashier.setBackground(new java.awt.Color(0, 181, 204));
        btn_refrashmanagecashier.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        btn_refrashmanagecashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btn_refrashmanagecashier.setContentAreaFilled(false);
        btn_refrashmanagecashier.setFocusPainted(false);
        btn_refrashmanagecashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrashmanagecashierActionPerformed(evt);
            }
        });
        panel_addcashier.add(btn_refrashmanagecashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, 40, 30));

        getContentPane().add(panel_addcashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1090, 768));

        panel_managecourse.setBackground(new java.awt.Color(255, 255, 255));
        panel_managecourse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_managecourse.setMinimumSize(new java.awt.Dimension(260, 768));
        panel_managecourse.setPreferredSize(new java.awt.Dimension(260, 1090));
        panel_managecourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimize3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize_window.png"))); // NOI18N
        btn_minimize3.setContentAreaFilled(false);
        btn_minimize3.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_minimize3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimize3ActionPerformed(evt);
            }
        });
        panel_managecourse.add(btn_minimize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 40, 30));

        btn_close3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window.png"))); // NOI18N
        btn_close3.setContentAreaFilled(false);
        btn_close3.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_close3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_close3ActionPerformed(evt);
            }
        });
        panel_managecourse.add(btn_close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 30, 30));

        label_addnewcourse.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N
        label_addnewcourse.setText("  Manage Course");
        panel_managecourse.add(label_addnewcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 70));

        text_searchcoursefees.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        text_searchcoursefees.setText("Search Course");
        text_searchcoursefees.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_searchcoursefees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_searchcoursefeesMouseClicked(evt);
            }
        });
        text_searchcoursefees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_searchcoursefeesKeyReleased(evt);
            }
        });
        panel_managecourse.add(text_searchcoursefees, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 290, 50));

        label_courseid.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        label_courseid.setText("Enter Course ID");
        panel_managecourse.add(label_courseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, 50));

        text_courseid.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        text_courseid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_courseid.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_courseid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_courseidMouseClicked(evt);
            }
        });
        text_courseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_courseidActionPerformed(evt);
            }
        });
        panel_managecourse.add(text_courseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 400, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel8.setText("Enter Course Description");
        panel_managecourse.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 210, 50));

        btn_updatecourse.setBackground(new java.awt.Color(0, 181, 204));
        btn_updatecourse.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btn_updatecourse.setText("Update");
        btn_updatecourse.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_updatecourse.setContentAreaFilled(false);
        btn_updatecourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatecourseActionPerformed(evt);
            }
        });
        panel_managecourse.add(btn_updatecourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 270, 50));

        btn_addcourse.setBackground(new java.awt.Color(0, 181, 204));
        btn_addcourse.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btn_addcourse.setText("Add");
        btn_addcourse.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_addcourse.setContentAreaFilled(false);
        btn_addcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcourseActionPerformed(evt);
            }
        });
        panel_managecourse.add(btn_addcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 270, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel10.setText("Enter Fees Amount");
        panel_managecourse.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, 50));

        text_coursedesc.setColumns(20);
        text_coursedesc.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        text_coursedesc.setRows(5);
        jScrollPane2.setViewportView(text_coursedesc);

        panel_managecourse.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 410, 90));

        table_course.setAutoCreateRowSorter(true);
        table_course.setBackground(new java.awt.Color(0, 181, 204));
        table_course.setBorder(new javax.swing.border.MatteBorder(null));
        table_course.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        table_course.setForeground(new java.awt.Color(255, 255, 255));
        table_course.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Fees", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_course.setGridColor(new java.awt.Color(0, 0, 0));
        table_course.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_course.setRowHeight(20);
        table_course.setSelectionBackground(new java.awt.Color(28, 92, 127));
        table_course.setShowVerticalLines(true
        );
        table_course.getTableHeader().setReorderingAllowed(false);
        table_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_courseMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_course);

        panel_managecourse.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 360, 600));

        text_coursefees.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        text_coursefees.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_coursefees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_coursefeesActionPerformed(evt);
            }
        });
        panel_managecourse.add(text_coursefees, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 400, 60));

        btn_refrashtable.setBackground(new java.awt.Color(0, 181, 204));
        btn_refrashtable.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        btn_refrashtable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btn_refrashtable.setContentAreaFilled(false);
        btn_refrashtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrashtableActionPerformed(evt);
            }
        });
        panel_managecourse.add(btn_refrashtable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 40, 30));

        btn_deletecourse.setBackground(new java.awt.Color(0, 181, 204));
        btn_deletecourse.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btn_deletecourse.setText("Delete");
        btn_deletecourse.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_deletecourse.setContentAreaFilled(false);
        btn_deletecourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletecourseActionPerformed(evt);
            }
        });
        panel_managecourse.add(btn_deletecourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 650, 270, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 181, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel_managecourse.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, 620));

        label_coursename1.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        label_coursename1.setText("Enter Course name");
        panel_managecourse.add(label_coursename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 270, 50));

        text_coursename.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        text_coursename.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_coursename.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_coursename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_coursenameActionPerformed(evt);
            }
        });
        panel_managecourse.add(text_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 400, 60));

        btn_clearcourse.setBackground(new java.awt.Color(0, 181, 204));
        btn_clearcourse.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btn_clearcourse.setText("Clear");
        btn_clearcourse.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_clearcourse.setContentAreaFilled(false);
        btn_clearcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearcourseActionPerformed(evt);
            }
        });
        panel_managecourse.add(btn_clearcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 270, 50));

        getContentPane().add(panel_managecourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1090, 768));

        panel_transaction.setBackground(new java.awt.Color(255, 255, 255));
        panel_transaction.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_transaction.setPreferredSize(new java.awt.Dimension(260, 768));
        panel_transaction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize_window.png"))); // NOI18N
        btn_minimize1.setContentAreaFilled(false);
        btn_minimize1.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_minimize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimize1ActionPerformed(evt);
            }
        });
        panel_transaction.add(btn_minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 50, -1));

        btn_close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window.png"))); // NOI18N
        btn_close1.setContentAreaFilled(false);
        btn_close1.setPreferredSize(new java.awt.Dimension(60, 40));
        btn_close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_close1ActionPerformed(evt);
            }
        });
        panel_transaction.add(btn_close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 50, -1));

        table_transaction.setAutoCreateRowSorter(true);
        table_transaction.setBackground(new java.awt.Color(0, 181, 204));
        table_transaction.setBorder(new javax.swing.border.MatteBorder(null));
        table_transaction.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        table_transaction.setForeground(new java.awt.Color(255, 255, 255));
        table_transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Username", "Password", "Status of Active"
            }
        ));
        table_transaction.setEnabled(false);
        table_transaction.setFocusable(false);
        table_transaction.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_transaction.setRowHeight(20);
        table_transaction.setSelectionBackground(new java.awt.Color(0, 181, 255));
        table_transaction.setShowVerticalLines(true
        );
        table_transaction.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(table_transaction);

        panel_transaction.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 950, 380));

        label1.setBackground(new java.awt.Color(0, 181, 204));
        label1.setFont(new java.awt.Font("Segoe UI Light", 1, 25)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 181, 204));
        label1.setText("Transaction Details");
        panel_transaction.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 40));

        getContentPane().add(panel_transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1140, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizeActionPerformed
            this.setState(this.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_minimizeActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
            System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_closeActionPerformed

    private void adminbtn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn_homeActionPerformed
         panel_home.setVisible(true);
            addcashier_clear();
         panel_addcashier.setVisible(false);
          panel_managecourse.setVisible(false);
          panel_transaction.setVisible(false);
    }//GEN-LAST:event_adminbtn_homeActionPerformed

    private void adminbtn_addcashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn_addcashierActionPerformed
          panel_addcashier.setVisible(true);
        panel_home.setVisible(false);
      panel_transaction.setVisible(false);
       panel_managecourse.setVisible(false);
    }//GEN-LAST:event_adminbtn_addcashierActionPerformed

    private void adminbtn_managecourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn_managecourseActionPerformed
        panel_managecourse.setVisible(true);
        panel_home.setVisible(false);
         //changecolor_panel(2);
         panel_addcashier.setVisible(false);
       panel_transaction.setVisible(false);  
    }//GEN-LAST:event_adminbtn_managecourseActionPerformed

    private void adminbtn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn_logoutActionPerformed
        // TODO add your handling code here:
        LoginForm lf=new LoginForm();
        lf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminbtn_logoutActionPerformed

    private void text_cashieremailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cashieremailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cashieremailActionPerformed

    private void text_cashierusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cashierusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cashierusernameActionPerformed

    private void btn_exportexcelsheetcashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportexcelsheetcashierActionPerformed
            
    }//GEN-LAST:event_btn_exportexcelsheetcashierActionPerformed
private void addcashier_clear()
{
        text_cashierusername.setText("");
        text_cashierid.setText("");
        text_cashierpassword.setText("");
        text_cashieraddress.setText("");
        text_cashiercontect.setText("");
        text_cashieremail.setText("");
        text_cashierid.requestFocus();
}

    private void btn_addcashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcashierActionPerformed
        int s;
        if (combobox_status.getSelectedItem().toString()=="Active") {
            s=1;
        }
        else{
            s=0;
        }

        try {
            String q="INSERT INTO `cashier_details`(`id`, `username`, `password`, `address`, `contectno`, `email`, `status`) VALUES ('"+text_cashierid.getText()+"','"+text_cashierusername.getText()+"','"+text_cashierpassword.getText()+"','"+text_cashieraddress.getText()+"','"+text_cashiercontect.getText()+"','"+text_cashieremail.getText()+"','"+s+"')";
               int i= c.st.executeUpdate(q);
                if (i > 0) {
                        JOptionPane.showMessageDialog(this,"Cashier Successfull Added !");
                        DefaultTableModel model=(DefaultTableModel) table_cashier.getModel();
                        while(model.getRowCount()>0){
                        model.setRowCount(0); }
                         table_cashier();
                }else{
                     JOptionPane.showMessageDialog(this,"Some thing is Problem !");
                }
             }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        addcashier_clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addcashierActionPerformed

    private void text_courseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_courseidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_courseidActionPerformed

    private void btn_updatecourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatecourseActionPerformed
        if(text_courseid.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this,"Please Enter Course ID");
       text_courseid.requestFocus();
        
       }
        else{
                try {
            String q="UPDATE `course_details` SET `course_id`='"+text_courseid.getText()+"', `course_name`='"+text_coursename.getText()+"',`course_fees`='"+text_coursefees.getText()+"',`course_description`='"+text_coursedesc.getText()+"' where `course_id`='"+text_courseid.getText()+"' ";
             int i=c.st.executeUpdate(q);
              if (i > 0) {
            JOptionPane.showMessageDialog(this,"Course Successfull Updated !");
             DefaultTableModel model=(DefaultTableModel) table_course.getModel();
            while(model.getRowCount()>0){
            model.setRowCount(0); }
            course_table();
             } else {
            JOptionPane.showMessageDialog(this,"Some thing is Problem !");
            course_clear();
                    }
               }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
                    }
        }
        course_clear();
    }//GEN-LAST:event_btn_updatecourseActionPerformed
private void course_table(){
      try{
          c.st =c.cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
          c.st =c.cn.createStatement();
           String q="SELECT * FROM `course_details` ";
           c.rs=c.st.executeQuery(q);
                        while(c.rs.next())
                       {
                                String cid=c.rs.getString(1);
                                String name=c.rs.getString(2);
                                String fees=c.rs.getString(3);
                                String desc=c.rs.getString(4);
                                Object [] content={cid,name,fees,desc};
                                DefaultTableModel model=(DefaultTableModel) table_course.getModel();
                                model.addRow(content);
                               // model.fireTableDateChanged();
                      }
           }
           catch(Exception a )
           {
                   JOptionPane.showMessageDialog(this,"Exception Is"+a.getMessage());
           }
    }
    private void btn_addcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcourseActionPerformed
        //connection
       // DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
       //SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
     //  String sdate=df.format(start_date.getDate());
      //  String edate=df.format(end_date.getDate());       
        try {
            String q="INSERT INTO `course_details` (`course_id`, `course_name`,`course_fees`, `course_description`) VALUES ('"+text_courseid.getText()+"', '"+text_coursename.getText()+"','"+text_coursefees.getText()+"', '"+text_coursedesc.getText()+"')";
            int i= c.st.executeUpdate(q);
             if (i > 0) {
            JOptionPane.showMessageDialog(this,"Course Successfull added !");
             DefaultTableModel model=(DefaultTableModel) table_course.getModel();
            while(model.getRowCount()>0){
            model.setRowCount(0); }
             course_table();
             } else {
            JOptionPane.showMessageDialog(this,"Some thing is Problem !");
              }
            course_clear();
              
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }


    }//GEN-LAST:event_btn_addcourseActionPerformed

    private void btn_minimize3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimize3ActionPerformed
            this.setState(this.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_minimize3ActionPerformed

    private void btn_close3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_close3ActionPerformed
          System.exit(0); //TODO add your handling code here:
    }//GEN-LAST:event_btn_close3ActionPerformed

    private void btn_minimize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimize2ActionPerformed
        this.setState(this.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_minimize2ActionPerformed

    private void btn_close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_close2ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_close2ActionPerformed

    private void btn_minimize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_minimize1ActionPerformed

    private void btn_close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_close1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_close1ActionPerformed

    private void text_coursefeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_coursefeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_coursefeesActionPerformed

    private void text_searchcoursefeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_searchcoursefeesMouseClicked
        text_searchcoursefees.setText("");
    }//GEN-LAST:event_text_searchcoursefeesMouseClicked

    private void btn_refrashtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrashtableActionPerformed
        DefaultTableModel model=(DefaultTableModel) table_course.getModel();
            while(model.getRowCount()>0){
            model.setRowCount(0); }
             course_table();       
      
    }//GEN-LAST:event_btn_refrashtableActionPerformed
private void course_clear()
{
    text_coursename.setText("");
    text_coursedesc.setText("");
    text_courseid.setText("");
    text_coursefees.setText("");
}
    private void btn_deletecourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletecourseActionPerformed
        if(text_courseid.getText()=="")
        {
        JOptionPane.showMessageDialog(this,"Please Enter Course ID");
       text_courseid.requestFocus();
        
       }
        else{
        try {
            String q="DELETE FROM `course_details` WHERE `course_id`= '"+text_courseid.getText()+"' ";
             int i=c.st.executeUpdate(q);
             if (i > 0) {
            JOptionPane.showMessageDialog(this,"Course Successfull Deleted !");
             DefaultTableModel model=(DefaultTableModel) table_course.getModel();
            while(model.getRowCount()>0){
            model.setRowCount(0); }
            course_table();
             } else {
            JOptionPane.showMessageDialog(this,"Some thing is Problem !");
            }
            course_clear();
              
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }
    }//GEN-LAST:event_btn_deletecourseActionPerformed

    private void text_coursenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_coursenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_coursenameActionPerformed

    private void text_courseidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_courseidMouseClicked
      text_courseid.setText("");
    }//GEN-LAST:event_text_courseidMouseClicked

    private void table_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_courseMouseClicked
        int i= table_course.getSelectedRow();
        //TableModel model =table_course.getModel();
        DefaultTableModel model=(DefaultTableModel) table_course.getModel();
        text_courseid.setText(model.getValueAt(i,0).toString());
        text_coursename.setText(model.getValueAt(i,1).toString());
        text_coursefees.setText(model.getValueAt(i,2).toString());
        text_coursedesc.setText(model.getValueAt(i,3).toString());
    }//GEN-LAST:event_table_courseMouseClicked

    private void btn_clearcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearcourseActionPerformed
        course_clear();
    }//GEN-LAST:event_btn_clearcourseActionPerformed

    private void text_cashieridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cashieridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cashieridActionPerformed

    private void text_cashierpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cashierpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cashierpasswordActionPerformed

    private void text_cashiercontectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cashiercontectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cashiercontectActionPerformed

    private void btn_updatecashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatecashierActionPerformed
                        int s;
                         if (combobox_status.getSelectedItem().toString()=="Active") {
                             s=1;
                         }
                         else{
                             s=0;
                         }

                         try {
                             String q="UPDATE `cashier_details` SET `username`='"+text_cashierusername.getText()+"',`password`='"+text_cashierpassword.getText()+"',`address`='"+text_cashieraddress.getText()+"',`contectno`='"+text_cashiercontect.getText()+"',`email`='"+text_cashieremail.getText()+"',`status`='"+s+"' WHERE `id`='"+text_cashierid.getText()+"' ";
                                int i= c.st.executeUpdate(q);
                                 if (i > 0) {
                                         JOptionPane.showMessageDialog(this,"Cashier Successfull Updated !");
                                         DefaultTableModel model=(DefaultTableModel) table_cashier.getModel();
                                         while(model.getRowCount()>0){
                                         model.setRowCount(0); }
                                          table_cashier();
                                 }else{
                                      JOptionPane.showMessageDialog(this,"Some thing is Problem !");
                                 }
                              }
                         catch (Exception e) {
                             JOptionPane.showMessageDialog(this,e.getMessage());
                         }
                         addcashier_clear();
    }//GEN-LAST:event_btn_updatecashierActionPerformed

    private void btn_deletecashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletecashierActionPerformed
                        try {
                             String q="DELETE FROM `cashier_details` WHERE `id`='"+text_cashierid.getText()+"' ";
                                int i= c.st.executeUpdate(q);
                                 if (i > 0) {
                                         JOptionPane.showMessageDialog(this,"Cashier Successfull Deleted !");
                                         DefaultTableModel model=(DefaultTableModel) table_cashier.getModel();
                                         while(model.getRowCount()>0){
                                         model.setRowCount(0); }
                                          table_cashier();
                                 }else{
                                      JOptionPane.showMessageDialog(this,"Some thing is Problem !");
                                 }
                              }
                         catch (Exception e) {
                             JOptionPane.showMessageDialog(this,e.getMessage());
                         }
                        addcashier_clear();
    }//GEN-LAST:event_btn_deletecashierActionPerformed

    private void table_cashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_cashierMouseClicked
        int i= table_cashier.getSelectedRow();
        //TableModel model =table_course.getModel();
        DefaultTableModel model=(DefaultTableModel) table_cashier.getModel();
        text_cashierid.setText(model.getValueAt(i,0).toString());
        text_cashierusername.setText(model.getValueAt(i,1).toString());
        text_cashierpassword.setText(model.getValueAt(i,2).toString());
        text_cashieraddress.setText(model.getValueAt(i,3).toString());
        text_cashiercontect.setText(model.getValueAt(i,4).toString());
        text_cashieremail.setText(model.getValueAt(i,5).toString());
        combobox_status.setSelectedIndex((int) model.getValueAt(i,6));
    }//GEN-LAST:event_table_cashierMouseClicked

    private void btn_clearaddcashier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearaddcashier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearaddcashier1ActionPerformed
        String path=null,fnm=null; 
    private void btn_backupdatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backupdatabaseActionPerformed
         JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
       
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        try {
                File f = chooser.getSelectedFile();
                path=f.getAbsolutePath();
                path= path.replace('\\','/');
                path=path+"_"+date+".sql";
                text_backuppath.setText(path);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_backupdatabaseActionPerformed

    private void text_backuppathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_backuppathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_backuppathActionPerformed

    private void btn_backupdatabase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backupdatabase1ActionPerformed
       Process p=null;
        try {
            String dbUser="root";
            String dbPass="";
            String dbName="feesmanagement";
            Runtime rt=Runtime.getRuntime();
            String cmd = "C:/xampp/mysql/bin/mysqldum.exe  p -u" + dbUser + " -p" + dbPass + " --database " + dbName + " -r " + path;
            //p = rt.exec("C:/xampp/mysql/bin/mysqldump.exe -root -p --add -B feesmanagemet -r"+path);
            p = rt.exec(cmd);
            int i= p.waitFor();
            if(i==0){
            JOptionPane.showMessageDialog(this,"Backup Sucessfull !");
                    }else{
            JOptionPane.showMessageDialog(this,"Can't Backup !");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_backupdatabase1ActionPerformed

    private void text_searchcoursefeesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_searchcoursefeesKeyReleased
        DefaultTableModel model = (DefaultTableModel) table_course.getModel();
        String search = text_searchcoursefees.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        table_course.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_text_searchcoursefeesKeyReleased

    private void text_searchcashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_searchcashierMouseClicked
        text_searchcashier.setText("");
    }//GEN-LAST:event_text_searchcashierMouseClicked

    private void text_searchcashierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_searchcashierKeyReleased
         DefaultTableModel model = (DefaultTableModel) table_cashier.getModel();
        String search = text_searchcashier.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        table_cashier.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search)); // TODO add your handling code here:
    }//GEN-LAST:event_text_searchcashierKeyReleased

    private void btn_refrashmanagecashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrashmanagecashierActionPerformed
                            DefaultTableModel model = (DefaultTableModel) table_cashier.getModel();
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }
        table_cashier();
    }//GEN-LAST:event_btn_refrashmanagecashierActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin_slidepanel;
    private javax.swing.JButton adminbtn_addcashier;
    private javax.swing.JButton adminbtn_home;
    private javax.swing.JButton adminbtn_logout;
    private javax.swing.JButton adminbtn_managecourse;
    private javax.swing.JButton btn_addcashier;
    private javax.swing.JButton btn_addcourse;
    private javax.swing.JButton btn_backupdatabase;
    private javax.swing.JButton btn_backupdatabase1;
    private javax.swing.JButton btn_clearaddcashier1;
    private javax.swing.JButton btn_clearcourse;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_close1;
    private javax.swing.JButton btn_close2;
    private javax.swing.JButton btn_close3;
    private javax.swing.JButton btn_deletecashier;
    private javax.swing.JButton btn_deletecourse;
    private javax.swing.JButton btn_exportexcelsheetcashier;
    private javax.swing.JButton btn_minimize;
    private javax.swing.JButton btn_minimize1;
    private javax.swing.JButton btn_minimize2;
    private javax.swing.JButton btn_minimize3;
    private javax.swing.JButton btn_refrashmanagecashier;
    private javax.swing.JButton btn_refrashtable;
    private javax.swing.JButton btn_updatecashier;
    private javax.swing.JButton btn_updatecourse;
    private javax.swing.JComboBox<String> combobox_status;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label_addnewcourse;
    private javax.swing.JLabel label_courseid;
    private javax.swing.JLabel label_coursename1;
    private javax.swing.JLabel label_datetime;
    public javax.swing.JLabel label_name;
    private javax.swing.JLabel label_titlebar1;
    public javax.swing.JPanel panel_addcashier;
    private javax.swing.JPanel panel_adminaddcashier;
    private javax.swing.JPanel panel_adminhome;
    private javax.swing.JPanel panel_adminlogout;
    private javax.swing.JPanel panel_adminmanagefees;
    private javax.swing.JPanel panel_home;
    public javax.swing.JPanel panel_managecourse;
    private javax.swing.JPanel panel_transaction;
    private javax.swing.JTable table_cashier;
    private javax.swing.JTable table_cashierhome;
    private javax.swing.JTable table_course;
    private javax.swing.JTable table_transaction;
    private javax.swing.JTextField text_backuppath;
    private javax.swing.JTextArea text_cashieraddress;
    private javax.swing.JTextField text_cashiercontect;
    private javax.swing.JTextField text_cashieremail;
    private javax.swing.JTextField text_cashierid;
    private javax.swing.JTextField text_cashierpassword;
    private javax.swing.JTextField text_cashierusername;
    private javax.swing.JTextArea text_coursedesc;
    private javax.swing.JTextField text_coursefees;
    private javax.swing.JTextField text_courseid;
    private javax.swing.JTextField text_coursename;
    private javax.swing.JTextField text_searchcashier;
    private javax.swing.JTextField text_searchcoursefees;
    // End of variables declaration//GEN-END:variables
}
