/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feesmanagment;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.net.*;

/**
 *
 * @author STUD
 */
public class LoginForm extends javax.swing.JFrame {
Connect c=new Connect();
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
    
        this.setUndecorated(true); //remove title bar
      //this.setAlwaysOnTop(true); //for top
    this.setResizable(false);
       
      initComponents();
           this.setLocationRelativeTo(null);
           FeesManagment f=new FeesManagment();
           f.connect();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Label_roll = new javax.swing.JLabel();
        Label_admin = new javax.swing.JLabel();
        radiobutton_cashier = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radiobutton_admin = new javax.swing.JRadioButton();
        jLabel_inven = new javax.swing.JLabel();
        jLabel_inven3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_username = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        text_password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        label_login = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        btn_minimize = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel_SoftZyd = new javax.swing.JLabel();
        jLabel_inven1 = new javax.swing.JLabel();
        label_passwordshow = new javax.swing.JLabel();
        jLabel_inven4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 181, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_roll.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        Label_roll.setForeground(new java.awt.Color(255, 255, 255));
        Label_roll.setText("Choose Your Role");
        jPanel2.add(Label_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 40));

        Label_admin.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        Label_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-admin-settings-male-100 (1).png"))); // NOI18N
        jPanel2.add(Label_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, -1));

        radiobutton_cashier.setBackground(new java.awt.Color(0, 181, 204));
        buttonGroup1.add(radiobutton_cashier);
        radiobutton_cashier.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        radiobutton_cashier.setForeground(new java.awt.Color(255, 255, 255));
        radiobutton_cashier.setText("Cashier");
        radiobutton_cashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton_cashierActionPerformed(evt);
            }
        });
        jPanel2.add(radiobutton_cashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cashier.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 120, -1));

        radiobutton_admin.setBackground(new java.awt.Color(0, 181, 204));
        buttonGroup1.add(radiobutton_admin);
        radiobutton_admin.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        radiobutton_admin.setForeground(new java.awt.Color(255, 255, 255));
        radiobutton_admin.setText("Admin");
        radiobutton_admin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radiobutton_adminStateChanged(evt);
            }
        });
        radiobutton_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton_adminActionPerformed(evt);
            }
        });
        jPanel2.add(radiobutton_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, -1));

        jLabel_inven.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel_inven.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_inven.setText("Version :- 1.2.25");
        jPanel2.add(jLabel_inven, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 170, 50));

        jLabel_inven3.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel_inven3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_inven3.setText("Fees Management System");
        jPanel2.add(jLabel_inven3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 250, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 670));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_username.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        label_username.setText("Enter Username");
        jPanel1.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 180, -1));

        text_username.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        text_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        text_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 470, 45));

        label_password.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        label_password.setText("Enter Password");
        jPanel1.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 170, -1));

        text_password.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        text_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 440, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        label_login.setBackground(new java.awt.Color(0, 181, 204));
        label_login.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        label_login.setText("Select your Role");
        jPanel1.add(label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 390, 50));

        btn_cancel.setBackground(new java.awt.Color(0, 181, 204));
        btn_cancel.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_cancel.setContentAreaFilled(false);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 190, 40));

        btn_login.setBackground(new java.awt.Color(0, 181, 204));
        btn_login.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        btn_login.setText("Login");
        btn_login.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        btn_login.setContentAreaFilled(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 190, 40));

        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize_window.png"))); // NOI18N
        btn_minimize.setContentAreaFilled(false);
        btn_minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 40));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window.png"))); // NOI18N
        btn_close.setContentAreaFilled(false);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px.png"))); // NOI18N
        jButton2.setToolTipText("Twitter");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px_2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, 28));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_2.png"))); // NOI18N
        jButton3.setToolTipText("Facebook");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_7.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, 28));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px.png"))); // NOI18N
        jButton4.setToolTipText("Instagram");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px_3.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, -1, 28));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        jButton6.setToolTipText("YouTube");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, -1, 28));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        jButton5.setToolTipText("Email");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, 28));

        jLabel_SoftZyd.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel_SoftZyd.setForeground(new java.awt.Color(0, 181, 204));
        jLabel_SoftZyd.setText("Mahida Softwere Solution");
        jLabel_SoftZyd.setToolTipText("");
        jPanel1.add(jLabel_SoftZyd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 590, 70));

        jLabel_inven1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel_inven1.setForeground(new java.awt.Color(0, 181, 204));
        jLabel_inven1.setText("Visite our Official Website");
        jLabel_inven1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_inven1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_inven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 170, 30));

        label_passwordshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paaswordicon.png"))); // NOI18N
        label_passwordshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_passwordshowMouseClicked(evt);
            }
        });
        jPanel1.add(label_passwordshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 40, 40));

        jLabel_inven4.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel_inven4.setForeground(new java.awt.Color(0, 181, 204));
        jLabel_inven4.setText("Power By");
        jPanel1.add(jLabel_inven4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 620, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        text_username.setText("");
        text_password.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
   
            // TODO add your handling code here:
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void radiobutton_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobutton_adminActionPerformed
       label_login.setText(" Log In as Admin");
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobutton_adminActionPerformed

    private void text_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameActionPerformed

    private void radiobutton_adminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radiobutton_adminStateChanged

    }//GEN-LAST:event_radiobutton_adminStateChanged

    private void radiobutton_cashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobutton_cashierActionPerformed
          label_login.setText(" Log In as Cashier");
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobutton_cashierActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
       text_username.setText("");
       text_password.setText("");
       text_username.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String un,pwd;    
        
            
        if( ! text_username.getText().isEmpty() && ! text_username.getText().isEmpty())
        {
            un=text_username.getText();
            pwd=text_password.getText();
                    if(radiobutton_admin.isSelected())
                    {
                        try{
                       String query ="SELECT * FROM `admin_details` WHERE username=? and password=?";
                       c.ps=c.cn.prepareStatement(query);
                       c.ps.setString(1,un);
                       c.ps.setString(2,pwd);
                       c.rs=c.ps.executeQuery();
                            if(c.rs.next()){
                                JOptionPane.showMessageDialog(this,"Password match  your are login.."+c.rs.getString("username"));
                                String user=text_username.getText();
                                Admin_home ah=new Admin_home();
                                ah .setVisible(true);
                                ah.label(user);
                                this.setVisible(false);
                                }
                             else
                                {JOptionPane.showMessageDialog(this,"username & password not match");}
                                }catch(SQLException e ){
                                JOptionPane.showMessageDialog(this, e.getMessage());
                                }
                    }
                    else if(radiobutton_cashier.isSelected())
                    {
                       
                         try{
                                    String query ="SELECT * FROM `cashier_details` WHERE `username` = ? AND `password` = ? AND `status` = ?";
                                    c.ps=c.cn.prepareStatement(query);
                                    c.ps.setString(1,un);
                                    c.ps.setString(2,pwd);
                                    c.ps.setString(3, "1");
                                    c.rs=c.ps.executeQuery();

                                    if(c.rs.next()){
                                        Cashier_home ch=new Cashier_home();
                                        JOptionPane.showMessageDialog(this,"Password match  your are login.."+c.rs.getString("username"));
                                         ch.setVisible(true);
                                         String user=text_username.getText();
                                         ch.label_name.setText("Role played by:-"+user);
                                        this.setVisible(false);
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(this,"username & password not match");}
                                    }
                                    catch(SQLException e ){
                                    JOptionPane.showMessageDialog(this, e.getMessage());
                                    }

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Please Select Your Role First...");
                    }       
        }else
        {               JOptionPane.showMessageDialog(this,"Please Enter Value..");
        }
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizeActionPerformed
                    this.setState(this.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_minimizeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             try{
                 String url = "https://twitter.com/Twitter?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor";
             java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
          }
             catch(Exception a)
             {  }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   try{
                 String url = "https://www.facebook.com";
             java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
          }
             catch(Exception a)
             {  }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   try{
                 String url = "https://www.instagram.com";
             java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
          }
             catch(Exception a)
             {  }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   try{
                 String url = "https://www.youtube.com";
             java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
          }
             catch(Exception a)
             {  }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           try{
                 String url = "https://www.gmail.com";
             java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
          }
             catch(Exception a)
             {  }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel_inven1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_inven1MouseClicked
              try{
                 String url = "https://info-itlearner.blogspot.com";
             java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
          }
             catch(Exception a)
             {  }
    }//GEN-LAST:event_jLabel_inven1MouseClicked
int i=0;
    private void label_passwordshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_passwordshowMouseClicked

        if (i==0) {
            text_password.setEchoChar((char) 0);
            i=1;
        } else if(i==1) {
            text_password.setEchoChar('*');
            i=0;
        }
    }//GEN-LAST:event_label_passwordshowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_admin;
    private javax.swing.JLabel Label_roll;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_minimize;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_SoftZyd;
    private javax.swing.JLabel jLabel_inven;
    private javax.swing.JLabel jLabel_inven1;
    private javax.swing.JLabel jLabel_inven3;
    private javax.swing.JLabel jLabel_inven4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_passwordshow;
    private javax.swing.JLabel label_username;
    private javax.swing.JRadioButton radiobutton_admin;
    private javax.swing.JRadioButton radiobutton_cashier;
    private javax.swing.JPasswordField text_password;
    private javax.swing.JTextField text_username;
    // End of variables declaration//GEN-END:variables
}
